export const countries = ['Nigeria', 'Ghana', 'Cameroon'];

export const countriesStatesAndLocalGovt = [
  {
    country: 'Nigeria',
    countryShortCode: 'NG',
    countryPhoneCode: '+234',
    countryCurrencyCode: 'NGN',
    states: [
      {
        state: 'Abia',
        localGovt: [
          'Aba North',
          'Aba South',
          'Arochukwu',
          'Bende',
          'Ikawuno',
          'Ikwuano',
          'Isiala-Ngwa North',
          'Isiala-Ngwa South',
          'Isuikwuato',
          'Umu Nneochi',
          'Obi Ngwa',
          'Obioma Ngwa',
          'Ohafia',
          'Ohaozara',
          'Osisioma',
          'Ugwunagbo',
          'Ukwa West',
          'Ukwa East',
          'Umuahia North',
          'Umuahia South',
        ],
      },
      {
        state: 'Adamawa',
        localGovt: [
          'Demsa',
          'Fufore',
          'Ganye',
          'Girei',
          'Gombi',
          'Guyuk',
          'Hong',
          'Jada',
          'Lamurde',
          'Madagali',
          'Maiha',
          'Mayo-Belwa',
          'Michika',
          'Mubi-North',
          'Mubi-South',
          'Numan',
          'Shelleng',
          'Song',
          'Toungo',
          'Yola North',
          'Yola South',
        ],
      },
      {
        state: 'Akwa Ibom',
        localGovt: [
          'Abak',
          'Eastern-Obolo',
          'Eket',
          'Esit-Eket',
          'Essien-Udim',
          'Etim-Ekpo',
          'Etinan',
          'Ibeno',
          'Ibesikpo-Asutan',
          'Ibiono-Ibom',
          'Ika',
          'Ikono',
          'Ikot-Abasi',
          'Ikot-Ekpene',
          'Ini',
          'Itu',
          'Mbo',
          'Mkpat-Enin',
          'Nsit-Atai',
          'Nsit-Ibom',
          'Nsit-Ubium',
          'Obot-Akara',
          'Okobo',
          'Onna',
          'Oron',
          'Oruk Anam',
          'Udung-Uko',
          'Ukanafun',
          'Urue-Offong/Oruko',
          'Uruan',
          'Uyo',
        ],
      },
      {
        state: 'Anambra',
        localGovt: [
          'Aguata',
          'Anambra East',
          'Anambra West',
          'Anaocha',
          'Awka North',
          'Awka South',
          'Ayamelum',
          'Dunukofia',
          'Ekwusigo',
          'Idemili-North',
          'Idemili-South',
          'Ihiala',
          'Njikoka',
          'Nnewi-North',
          'Nnewi-South',
          'Ogbaru',
          'Onitsha-North',
          'Onitsha-South',
          'Orumba-North',
          'Orumba-South',
        ],
      },
      {
        state: 'Bauchi',
        localGovt: [
          'Alkaleri',
          'Bauchi',
          'Bogoro',
          'Damban',
          'Darazo',
          'Dass',
          'Gamawa',
          'Ganjuwa',
          'Giade',
          'Itas/Gadau',
          "Jama'Are",
          'Katagum',
          'Kirfi',
          'Misau',
          'Ningi',
          'Shira',
          'Tafawa-Balewa',
          'Toro',
          'Warji',
          'Zaki',
        ],
      },
      {
        state: 'Benue',
        localGovt: [
          'Ado',
          'Agatu',
          'Apa',
          'Buruku',
          'Gboko',
          'Guma',
          'Gwer-East',
          'Gwer-West',
          'Katsina-Ala',
          'Konshisha',
          'Kwande',
          'Logo',
          'Makurdi',
          'Ogbadibo',
          'Ohimini',
          'Oju',
          'Okpokwu',
          'Otukpo',
          'Tarka',
          'Ukum',
          'Ushongo',
          'Vandeikya',
        ],
      },
      {
        state: 'Borno',
        localGovt: [
          'Abadam',
          'Askira-Uba',
          'Bama',
          'Bayo',
          'Biu',
          'Chibok',
          'Damboa',
          'Dikwa',
          'Gubio',
          'Guzamala',
          'Gwoza',
          'Hawul',
          'Jere',
          'Kaga',
          'Kala/Balge',
          'Konduga',
          'Kukawa',
          'Kwaya-Kusar',
          'Mafa',
          'Magumeri',
          'Maiduguri',
          'Marte',
          'Mobbar',
          'Monguno',
          'Ngala',
          'Nganzai',
          'Shani',
        ],
      },
      {
        state: 'Bayelsa',
        localGovt: [
          'Brass',
          'Ekeremor',
          'Kolokuma/Opokuma',
          'Nembe',
          'Ogbia',
          'Sagbama',
          'Southern-Ijaw',
          'Yenagoa',
        ],
      },
      {
        state: 'Cross River',
        localGovt: [
          'Abi',
          'Akamkpa',
          'Akpabuyo',
          'Bakassi',
          'Bekwarra',
          'Biase',
          'Boki',
          'Calabar-Municipal',
          'Calabar-South',
          'Etung',
          'Ikom',
          'Obanliku',
          'Obubra',
          'Obudu',
          'Odukpani',
          'Ogoja',
          'Yakurr',
          'Yala',
        ],
      },
      {
        state: 'Delta',
        localGovt: [
          'Aniocha North',
          'Aniocha-North',
          'Aniocha-South',
          'Bomadi',
          'Burutu',
          'Ethiope-East',
          'Ethiope-West',
          'Ika-North-East',
          'Ika-South',
          'Isoko-North',
          'Isoko-South',
          'Ndokwa-East',
          'Ndokwa-West',
          'Okpe',
          'Oshimili-North',
          'Oshimili-South',
          'Patani',
          'Sapele',
          'Udu',
          'Ughelli-North',
          'Ughelli-South',
          'Ukwuani',
          'Uvwie',
          'Warri South-West',
          'Warri North',
          'Warri South',
        ],
      },
      {
        state: 'Ebonyi',
        localGovt: [
          'Abakaliki',
          'Afikpo-North',
          'Afikpo South (Edda)',
          'Ebonyi',
          'Ezza-North',
          'Ezza-South',
          'Ikwo',
          'Ishielu',
          'Ivo',
          'Izzi',
          'Ohaukwu',
          'Onicha',
        ],
      },
      {
        state: 'Edo',
        localGovt: [
          'Akoko Edo',
          'Egor',
          'Esan-Central',
          'Esan-North-East',
          'Esan-South-East',
          'Esan-West',
          'Etsako-Central',
          'Etsako-East',
          'Etsako-West',
          'Igueben',
          'Ikpoba-Okha',
          'Oredo',
          'Orhionmwon',
          'Ovia-North-East',
          'Ovia-South-West',
          'Owan East',
          'Owan-West',
          'Uhunmwonde',
        ],
      },
      {
        state: 'Ekiti',
        localGovt: [
          'Ado-Ekiti',
          'Efon',
          'Ekiti-East',
          'Ekiti-South-West',
          'Ekiti-West',
          'Emure',
          'Gbonyin',
          'Ido-Osi',
          'Ijero',
          'Ikere',
          'Ikole',
          'Ilejemeje',
          'Irepodun/Ifelodun',
          'Ise-Orun',
          'Moba',
          'Oye',
        ],
      },
      {
        state: 'Enugu',
        localGovt: [
          'Aninri',
          'Awgu',
          'Enugu-East',
          'Enugu-North',
          'Enugu-South',
          'Ezeagu',
          'Igbo-Etiti',
          'Igbo-Eze-North',
          'Igbo-Eze-South',
          'Isi-Uzo',
          'Nkanu-East',
          'Nkanu-West',
          'Nsukka',
          'Oji-River',
          'Udenu',
          'Udi',
          'Uzo-Uwani',
        ],
      },
      {
        state: 'Federal Capital Territory',
        localGovt: ['Abuja', 'Kwali', 'Kuje', 'Gwagwalada', 'Bwari', 'Abaji'],
      },
      {
        state: 'Gombe',
        localGovt: [
          'Akko',
          'Balanga',
          'Billiri',
          'Dukku',
          'Funakaye',
          'Gombe',
          'Kaltungo',
          'Kwami',
          'Nafada',
          'Shongom',
          'Yamaltu/Deba',
        ],
      },
      {
        state: 'Imo',
        localGovt: [
          'Aboh-Mbaise',
          'Ahiazu-Mbaise',
          'Ehime-Mbano',
          'Ezinihitte',
          'Ideato-North',
          'Ideato-South',
          'Ihitte/Uboma',
          'Ikeduru',
          'Isiala-Mbano',
          'Isu',
          'Mbaitoli',
          'Ngor-Okpala',
          'Njaba',
          'Nkwerre',
          'Nwangele',
          'Obowo',
          'Oguta',
          'Ohaji-Egbema',
          'Okigwe',
          'Onuimo',
          'Orlu',
          'Orsu',
          'Oru-East',
          'Oru-West',
          'Owerri-Municipal',
          'Owerri-North',
          'Owerri-West',
        ],
      },
      {
        state: 'Jigawa',
        localGovt: [
          'Auyo',
          'Babura',
          'Biriniwa',
          'Birnin-Kudu',
          'Buji',
          'Dutse',
          'Gagarawa',
          'Garki',
          'Gumel',
          'Guri',
          'Gwaram',
          'Gwiwa',
          'Hadejia',
          'Jahun',
          'Kafin-Hausa',
          'Kaugama',
          'Kazaure',
          'Kiri kasama',
          'Maigatari',
          'Malam Madori',
          'Miga',
          'Ringim',
          'Roni',
          'Sule-Tankarkar',
          'Taura',
          'Yankwashi',
        ],
      },
      {
        state: 'Kebbi',
        localGovt: [
          'Aleiro',
          'Arewa-Dandi',
          'Argungu',
          'Augie',
          'Bagudo',
          'Birnin-Kebbi',
          'Bunza',
          'Dandi',
          'Fakai',
          'Gwandu',
          'Jega',
          'Kalgo',
          'Koko-Besse',
          'Maiyama',
          'Ngaski',
          'Sakaba',
          'Shanga',
          'Suru',
          'Wasagu/Danko',
          'Yauri',
          'Zuru',
        ],
      },
      {
        state: 'Kaduna',
        localGovt: [
          'Birnin-Gwari',
          'Chikun',
          'Giwa',
          'Igabi',
          'Ikara',
          'Jaba',
          "Jema'A",
          'Kachia',
          'Kaduna-North',
          'Kaduna-South',
          'Kagarko',
          'Kajuru',
          'Kaura',
          'Kauru',
          'Kubau',
          'Kudan',
          'Lere',
          'Makarfi',
          'Sabon-Gari',
          'Sanga',
          'Soba',
          'Zangon-Kataf',
          'Zaria',
        ],
      },
      {
        state: 'Kano',
        localGovt: [
          'Ajingi',
          'Albasu',
          'Bagwai',
          'Bebeji',
          'Bichi',
          'Bunkure',
          'Dala',
          'Dambatta',
          'Dawakin-Kudu',
          'Dawakin-Tofa',
          'Doguwa',
          'Fagge',
          'Gabasawa',
          'Garko',
          'Garun-Mallam',
          'Gaya',
          'Gezawa',
          'Gwale',
          'Gwarzo',
          'Kabo',
          'Kano-Municipal',
          'Karaye',
          'Kibiya',
          'Kiru',
          'Kumbotso',
          'Kunchi',
          'Kura',
          'Madobi',
          'Makoda',
          'Minjibir',
          'Nasarawa',
          'Rano',
          'Rimin-Gado',
          'Rogo',
          'Shanono',
          'Sumaila',
          'Takai',
          'Tarauni',
          'Tofa',
          'Tsanyawa',
          'Tudun-Wada',
          'Ungogo',
          'Warawa',
          'Wudil',
        ],
      },
      {
        state: 'Kogi',
        localGovt: [
          'Adavi',
          'Ajaokuta',
          'Ankpa',
          'Dekina',
          'Ibaji',
          'Idah',
          'Igalamela-Odolu',
          'Ijumu',
          'Kabba/Bunu',
          'Kogi',
          'Lokoja',
          'Mopa-Muro',
          'Ofu',
          'Ogori/Magongo',
          'Okehi',
          'Okene',
          'Olamaboro',
          'Omala',
          'Oyi',
          'Yagba-East',
          'Yagba-West',
        ],
      },
      {
        state: 'Katsina',
        localGovt: [
          'Bakori',
          'Batagarawa',
          'Batsari',
          'Baure',
          'Bindawa',
          'Charanchi',
          'Dan-Musa',
          'Dandume',
          'Danja',
          'Daura',
          'Dutsi',
          'Dutsin-Ma',
          'Faskari',
          'Funtua',
          'Ingawa',
          'Jibia',
          'Kafur',
          'Kaita',
          'Kankara',
          'Kankia',
          'Katsina',
          'Kurfi',
          'Kusada',
          'Mai-Adua',
          'Malumfashi',
          'Mani',
          'Mashi',
          'Matazu',
          'Musawa',
          'Rimi',
          'Sabuwa',
          'Safana',
          'Sandamu',
          'Zango',
        ],
      },
      {
        state: 'Kwara',
        localGovt: [
          'Asa',
          'Baruten',
          'Edu',
          'Ekiti (Araromi/Opin)',
          'Ilorin-East',
          'Ilorin-South',
          'Ilorin-West',
          'Isin',
          'Kaiama',
          'Moro',
          'Offa',
          'Oke-Ero',
          'Oyun',
          'Pategi',
        ],
      },
      {
        state: 'Lagos',
        localGovt: [
          'Agege',
          'Ajeromi-Ifelodun',
          'Alimosho',
          'Amuwo-Odofin',
          'Apapa',
          'Badagry',
          'Epe',
          'Eti-Osa',
          'Ibeju-Lekki',
          'Ifako-Ijaiye',
          'Ikeja',
          'Ikorodu',
          'Kosofe',
          'Lagos-Island',
          'Lagos-Mainland',
          'Mushin',
          'Ojo',
          'Oshodi-Isolo',
          'Shomolu',
          'Surulere',
          'Yewa-South',
        ],
      },
      {
        state: 'Nasarawa',
        localGovt: [
          'Akwanga',
          'Awe',
          'Doma',
          'Karu',
          'Keana',
          'Keffi',
          'Kokona',
          'Lafia',
          'Nasarawa',
          'Nasarawa-Eggon',
          'Obi',
          'Wamba',
          'Toto',
        ],
      },
      {
        state: 'Niger',
        localGovt: [
          'Agaie',
          'Agwara',
          'Bida',
          'Borgu',
          'Bosso',
          'Chanchaga',
          'Edati',
          'Gbako',
          'Gurara',
          'Katcha',
          'Kontagora',
          'Lapai',
          'Lavun',
          'Magama',
          'Mariga',
          'Mashegu',
          'Mokwa',
          'Moya',
          'Paikoro',
          'Rafi',
          'Rijau',
          'Shiroro',
          'Suleja',
          'Tafa',
          'Wushishi',
        ],
      },
      {
        state: 'Ogun',
        localGovt: [
          'Abeokuta-North',
          'Abeokuta-South',
          'Ado-Odo/Ota',
          'Ewekoro',
          'Ifo',
          'Ijebu-East',
          'Ijebu-North',
          'Ijebu-North-East',
          'Ijebu-Ode',
          'Ikenne',
          'Imeko-Afon',
          'Ipokia',
          'Obafemi-Owode',
          'Odeda',
          'Odogbolu',
          'Ogun-Waterside',
          'Remo-North',
          'Shagamu',
          'Yewa North',
        ],
      },
      {
        state: 'Ondo',
        localGovt: [
          'Akoko North-East',
          'Akoko North-West',
          'Akoko South-West',
          'Akoko South-East',
          'Akure-North',
          'Akure-South',
          'Ese-Odo',
          'Idanre',
          'Ifedore',
          'Ilaje',
          'Ile-Oluji-Okeigbo',
          'Irele',
          'Odigbo',
          'Okitipupa',
          'Ondo West',
          'Ondo-East',
          'Ose',
          'Owo',
        ],
      },
      {
        state: 'Osun',
        localGovt: [
          'Atakumosa West',
          'Atakumosa East',
          'Ayedaade',
          'Ayedire',
          'Boluwaduro',
          'Boripe',
          'Ede South',
          'Ede North',
          'Egbedore',
          'Ejigbo',
          'Ife North',
          'Ife South',
          'Ife-Central',
          'Ife-East',
          'Ifelodun',
          'Ila',
          'Ilesa-East',
          'Ilesa-West',
          'Irepodun',
          'Irewole',
          'Isokan',
          'Iwo',
          'Obokun',
          'Odo-Otin',
          'Ola Oluwa',
          'Olorunda',
          'Oriade',
          'Orolu',
          'Osogbo',
        ],
      },
      {
        state: 'Oyo',
        localGovt: [
          'Afijio',
          'Akinyele',
          'Atiba',
          'Atisbo',
          'Egbeda',
          'Ibadan North',
          'Ibadan North-East',
          'Ibadan North-West',
          'Ibadan South-East',
          'Ibadan South-West',
          'Ibarapa-Central',
          'Ibarapa-East',
          'Ibarapa-North',
          'Ido',
          'Ifedayo',
          'Irepo',
          'Iseyin',
          'Itesiwaju',
          'Iwajowa',
          'Kajola',
          'Lagelu',
          'Ogo-Oluwa',
          'Ogbomosho-North',
          'Ogbomosho-South',
          'Olorunsogo',
          'Oluyole',
          'Ona-Ara',
          'Orelope',
          'Ori-Ire',
          'Oyo-West',
          'Oyo-East',
          'Saki-East',
          'Saki-West',
          'Surulere',
        ],
      },
      {
        state: 'Plateau',
        localGovt: [
          'Barkin-Ladi',
          'Bassa',
          'Bokkos',
          'Jos-East',
          'Jos-North',
          'Jos-South',
          'Kanam',
          'Kanke',
          'Langtang-North',
          'Langtang-South',
          'Mangu',
          'Mikang',
          'Pankshin',
          "Qua'an Pan",
          'Riyom',
          'Shendam',
          'Wase',
        ],
      },
      {
        state: 'Rivers',
        localGovt: [
          'Abua/Odual',
          'Ahoada-East',
          'Ahoada-West',
          'Akuku Toru',
          'Andoni',
          'Asari-Toru',
          'Bonny',
          'Degema',
          'Eleme',
          'Emuoha',
          'Etche',
          'Gokana',
          'Ikwerre',
          'Khana',
          'Obio/Akpor',
          'Ogba-Egbema-Ndoni',
          'Ogba/Egbema/Ndoni',
          'Ogu/Bolo',
          'Okrika',
          'Omuma',
          'Opobo/Nkoro',
          'Oyigbo',
          'Port-Harcourt',
          'Tai',
        ],
      },
      {
        state: 'Sokoto',
        localGovt: [
          'Binji',
          'Bodinga',
          'Dange-Shuni',
          'Gada',
          'Goronyo',
          'Gudu',
          'Gwadabawa',
          'Illela',
          'Kebbe',
          'Kware',
          'Rabah',
          'Sabon Birni',
          'Shagari',
          'Silame',
          'Sokoto-North',
          'Sokoto-South',
          'Tambuwal',
          'Tangaza',
          'Tureta',
          'Wamako',
          'Wurno',
          'Yabo',
        ],
      },
      {
        state: 'Taraba',
        localGovt: [
          'Ardo-Kola',
          'Bali',
          'Donga',
          'Gashaka',
          'Gassol',
          'Ibi',
          'Jalingo',
          'Karim-Lamido',
          'Kurmi',
          'Lau',
          'Sardauna',
          'Takum',
          'Ussa',
          'Wukari',
          'Yorro',
          'Zing',
        ],
      },
      {
        state: 'Yobe',
        localGovt: [
          'Bade',
          'Bursari',
          'Damaturu',
          'Fika',
          'Fune',
          'Geidam',
          'Gujba',
          'Gulani',
          'Jakusko',
          'Karasuwa',
          'Machina',
          'Nangere',
          'Nguru',
          'Potiskum',
          'Tarmuwa',
          'Yunusari',
          'Yusufari',
        ],
      },
      {
        state: 'Zamfara',
        localGovt: [
          'Anka',
          'Bakura',
          'Birnin Magaji/Kiyaw',
          'Bukkuyum',
          'Bungudu',
          'Gummi',
          'Gusau',
          'Isa',
          'Kaura-Namoda',
          'Kiyawa',
          'Maradun',
          'Maru',
          'Shinkafi',
          'Talata-Mafara',
          'Tsafe',
          'Zurmi',
        ],
      },
    ],
  },
  {
    country: 'Ghana',
    countryShortCode: 'GH',
    countryPhoneCode: '+233',
    countryCurrencyCode: 'GHS',
    states: [
      {
        state: 'Greater Accra',
        localGovt: [
          'Accra',
          'Ada East',
          'Ada West',
          'Adenta',
          'Ashaiman',
          'Dangme East',
          'Dangme West',
          'Ga Central',
          'Ga East',
          'Ga South',
          'Ga West',
          'Kpone Katamanso',
          'La Dade Kotopon',
          'La Nkwantanang Madina',
          'Ledzokuku-Krowor',
          'Ningo Prampram',
          'Shai Osudoku',
          'Tema',
          'Weija Gbawe',
        ],
      },
      {
        state: 'Ashanti',
        localGovt: [
          'Adansi North',
          'Adansi South',
          'Afigya-Kwabre',
          'Ahafo-Ano North',
          'Ahafo-Ano South',
          'Amansie Central',
          'Amansie West',
          'Asante Akim Central',
          'Asante Akim North',
          'Asante Akim South',
          'Asokore Mampong',
          'Atwima Kwanwoma',
          'Atwima Mponua',
          'Atwima Nwabiagya',
          'Bekwai',
          'Bosome Freho',
          'Botsomtwe',
          'Ejisu-Juaben',
          'Ejura Sekyedumase',
          'Kumasi',
          'Kwabre East',
          'Mampong',
          'Obuasi',
          'Offinso North',
          'Offinso South',
          'Sekyere Afram Plains',
          'Sekyere Central',
          'Sekyere East',
          'Sekyere South',
        ],
      },
      {
        state: 'Brong Ahafo',
        localGovt: [
          'Asunafo North',
          'Asunafo South',
          'Asutifi North',
          'Asutifi South',
          'Atebubu-Amantin',
          'Banda',
          'Berekum',
          'Dormaa East',
          'Dormaa West',
          'Jaman North',
          'Jaman South',
          'Kintampo North',
          'Kintampo South',
          'Nkoranza North',
          'Nkoranza South',
          'Pru',
          'Sene',
          'Sunyani',
          'Sunyani West',
          'Tain',
          'Tano North',
          'Tano South',
          'Techiman',
          'Wenchi',
        ],
      },
    ],
  },
  {
    country: 'Cameroon',
    countryShortCode: 'CM',
    countryPhoneCode: '+237',
    countryCurrencyCode: 'XAF',
    states: [
      {
        state: 'Adamaoua',
        localGovt: ['Djérem', 'Faro-et-Déo', 'Mayo-Banyo', 'Mbéré', 'Vina'],
      },
      {
        state: 'Centre',
        localGovt: [
          'Haute-Sanaga',
          'Lekié',
          'Mbam-et-Inoubou',
          'Mbam-et-Kim',
          'Méfou-et-Afamba',
          'Méfou-et-Akono',
          'Mfoundi',
          'Nyong-et-Kéllé',
          'Nyong-et-Mfoumou',
        ],
      },
      {
        state: 'East',
        localGovt: ['Boumba-et-Ngoko', 'Haut-Nyong', 'Kadey', 'Lom-et-Djérem'],
      },
      {
        state: 'Far North',
        localGovt: [
          'Diamaré',
          'Logone-et-Chari',
          'Mayo-Danay',
          'Mayo-Kani',
          'Mayo-Sava',
          'Mayo-Tsanaga',
        ],
      },
      {
        state: 'Littoral',
        localGovt: ['Moungo', 'Nkam', 'Sanaga-Maritime', 'Wouri'],
      },
      {
        state: 'North',
        localGovt: ['Bénoué', 'Faro', 'Mayo-Louti', 'Mayo-Rey', 'Mayo-Tsanaga'],
      },
      {
        state: 'Northwest',
        localGovt: [
          'Bui',
          'Donga-Mantung',
          'Menchum',
          'Mezam',
          'Momo',
          'Ngo-Ketunjia',
        ],
      },
      {
        state: 'South',
        localGovt: ['Dja-et-Lobo', 'Mvila', 'Océan'],
      },
      {
        state: 'Southwest',
        localGovt: [
          'Fako',
          'Koupé-Manengouba',
          'Lebialem',
          'Manyu',
          'Meme',
          'Ndian',
        ],
      },
      {
        state: 'West',
        localGovt: [
          'Bamboutos',
          'Haut-Nkam',
          'Hauts-Plateaux',
          'Koung-Khi',
          'Menoua',
          'Mifi',
          'Ndé',
          'Noun',
        ],
      },

      {
        state: 'Northwest',
        localGovt: [
          'Bui',
          'Donga-Mantung',
          'Menchum',
          'Mezam',
          'Momo',
          'Ngo-Ketunjia',
        ],
      },
    ],
  },
];
